### ISSUE TITLE
Occasional crash coming out of rbkit_allocation_info.c:71

### ISSUE THREAD

**Issue by gnufied** [code-mancers/rbkit#98]
The backtrace is here:

```
(gdb) bt
#0  0x00005555555933ef in rgengc_check_relation (objspace=0x555555a499a0, objspace=0x555555a499a0, obj=11648) at gc.c:3563
#1  gc_mark_children (objspace=objspace@entry=0x555555a499a0, ptr=11648) at gc.c:3634
#2  0x0000555555593da8 in gc_mark_stacked_objects (objspace=0x555555a499a0) at gc.c:3978
#3  gc_marks_body (objspace=0x555555a499a0, full_mark=<optimized out>) at gc.c:4162
#4  0x000055555559655a in gc_marks (full_mark=0, objspace=0x555555a499a0) at gc.c:4523
#5  garbage_collect_body (objspace=objspace@entry=0x555555a499a0, full_mark=full_mark@entry=0, immediate_sweep=immediate_sweep@entry=1, reason=<optimized out>, reason@entry=512) at gc.c:5021
#6  0x000055555559445d in garbage_collect (objspace=objspace@entry=0x555555a499a0, full_mark=full_mark@entry=0, immediate_sweep=immediate_sweep@entry=1, reason=reason@entry=512) at gc.c:5074
#7  0x000055555559487d in garbage_collect (reason=512, immediate_sweep=1, full_mark=0, objspace=0x555555a499a0) at gc.c:5113
#8  garbage_collect_with_gvl (objspace=objspace@entry=0x555555a499a0, full_mark=full_mark@entry=0, reason=512, immediate_sweep=1) at gc.c:5096
#9  0x0000555555595c98 in objspace_malloc_increase (objspace=objspace@entry=0x555555a499a0, new_size=<optimized out>, old_size=old_size@entry=0, type=type@entry=MEMOP_TYPE_MALLOC, mem=0x55555cfbf140) at gc.c:6004
#10 0x000055555559a3e0 in objspace_xmalloc (size=<optimized out>, objspace=0x555555a499a0) at gc.c:6096
#11 ruby_xmalloc (size=size@entry=40) at gc.c:6158
#12 0x00007ffff4d2a915 in new_rbkit_allocation_info (tparg=tparg@entry=0x7fffffff72c0, str_table=0x5555580edb30, object_table=0x5555580eda50) at rbkit_allocation_info.c:71
#13 0x00007ffff4d2d188 in newobj_i (tpval=<optimized out>, data=0x5555580ebfd0) at rbkit_tracer.c:100
```

I am not entirely sure why we are using `ruby_xmalloc` there. @emilsoman ?

**Comment by gnufied** [comment]
Fixed by https://github.com/code-mancers/rbkit/pull/99 I haven't seen these after the fix.
